### ISSUE TITLE
Docker mounted folders and file permission issues

### ISSUE THREAD

**Issue by MariotteBoyle** [ulyssesrr/docker-rocm-gfx803#1]
Hi, I mounted the image and it works, but the folders and files it creates when mounting are **read only,** or have some **permission restrictions** that prevent me from deleting them or moving files into the folders, creating, etc, or even it didn't allowed Ubuntu to create thumbnails.

The workaround I used was to run `sudo nautilus` in Ubuntu (currently I'm on Arch). Is there a way to run it without this issue?

Regards.

**Comment by ulyssesrr** [comment]
Everything in executed as root inside the containers, as its is done in the AMD containers they are based on, thus the files created are owned by root. I've tried fixing this but it produced others issues, so mmost likely it will stay this way.

I advise you to change the ownership of the files back to your user, rather then running nautilus with sudo (root).
Example:
`sudo chown -R $USER foldername`
